export const ACTION_CHANGE_INPUT_VALUE = 'ACTION_CHANGE_INPUT_VALUE';

export const ADD_IMAGES_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_IMAGES_FAILURE = 'ADD_TODO_FAILURE';
export const ADD_IMAGES_STARTED = 'ADD_TODO_STARTED';